/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "foreground-rgb": "rgb(var(--foreground-rgb))",
        "background-start-rgb": "rgb(var(--background-start-rgb))",
        "background-end-rgb": "rgb(var(--background-end-rgb))",
        "brand-default": "var(--brand-default)",
        "brand-fainter": "var(--brand-fainter)",
        "brand-faint": "var(--brand-faint)",
        "brand-subtle": "var(--brand-subtle)",
        "brand-muted": "var(--brand-muted)",
        "brand-dark": "var(--brand-dark)",
        "brand-darker": "var(--brand-darker)",
        "secondary-accent": "var(--secondary-accent)",
        "secondary-accent2x": "var(--secondary-accent2x)",
        "secondary-dark": "var(--secondary-dark)",
        "secondary-darker": "var(--secondary-darker)",
        "secondary-darkest": "var(--secondary-darkest)",
        "secondary-default": "var(--secondary-default)",
        "secondary-faint": "var(--secondary-faint)",
        "secondary-fainter": "var(--secondary-fainter)",
        "gray-50": "var(--gray-50)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-950": "var(--gray-950)",
        black: "var(--black)",
        white: "var(--white)",
        "accent-yellow-light": "var(--accent-yellow-light)",
        "accent-yellow-dark": "var(--accent-yellow-dark)",
        "accent-skyblue-light": "var(--accent-skyblue-light)",
        "accent-skyblue-dark": "var(--accent-skyblue-dark)",
        "accent-green": "var(--accent-green)",
        "accent-red": "var(--accent-red)",
        "accent-darkgreen-dark": "var(--accent-darkgreen-dark)",
        "accent-darkgreen-light": "var(--accent-darkgreen-light)",
        "accent-purple-dark": "var(--accent-purple-dark)",
        "accent-purple-light": "var(--accent-purple-light)",
        "accent-pink-dark": "var(--accent-pink-dark)",
        "accent-pink-light": "var(--accent-pink-light)",
        "accent-maroon-dark": "var(--accent-maroon-dark)",
        "accent-maroon-light": "var(--accent-maroon-light)",
        accent: "var(--accent)",
        "accent-background": "var(--accent-background)",
        "border-default": "var(--border-default)",
        "text-light-default": "var(--text-light-default)",
        "text-light-muted": "var(--text-light-muted)",
        "text-light-subtle": "var(--text-light-subtle)",
        "text-light-faint": "var(--text-light-faint)",
        "text-light-link": "var(--text-light-link)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
